
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shreyas
 */
public class booking extends javax.swing.JFrame {

    /**
     * Creates new form booking
     */
    
    int movieId,index;
    String name;
    
    public booking() {
        initComponents();
        
    }

   public booking(int movieId, String name) throws SQLException {
        
         initComponents();
         this.movieId = movieId;
         this.name = name;
        JTxtMovName.setText(name);
        JTxtMovName.setEditable(false);
        
      
        
        
   fillTheatreCombo();
    
    }
   
   ArrayList<Integer> theatreIds =new ArrayList<>();
   
   private void fillTheatreCombo() throws SQLException{
       
       
       SQLDao obj = new SQLDao();
       
       ResultSet rs = obj.getTheatreFromOfMovie(movieId);
       
       if(rs.next()){
           theatreIds.add(rs.getInt(2));
           JComboTheatre.addItem(rs.getString(1));
           
           while(rs.next()){
               theatreIds.add(rs.getInt(2));
               JComboTheatre.addItem(rs.getString(1));
               
           }
           
           
       }else{
           JOptionPane.showMessageDialog(null, "Empty resultset");
       }
       
       
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        JTxtMovName = new javax.swing.JTextField();
        jf2 = new javax.swing.JTextField();
        jf4 = new javax.swing.JTextField();
        jf5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jc1 = new javax.swing.JComboBox<>();
        JComboTheatre = new javax.swing.JComboBox<>();
        jc2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOKING");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("               TICKET   BOOKING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 470, 46));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" CUSTOMER NAME        :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 233, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" CUSTOMER PHONE_NO    :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 213, 263, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText(" THEATRE NAME        :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 200, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("DAY            :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 120, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("SHOW TIME            :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 190, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MOVIE_NAME              :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 288, 210, 35));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NO_OF_TICKETS        :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 362, 210, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PAYMENT METHOD   :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 481, -1, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("PAYTM");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("DEBIT CARD");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 481, -1, -1));

        JTxtMovName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTxtMovName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtMovNameActionPerformed(evt);
            }
        });
        getContentPane().add(JTxtMovName, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 288, 250, 35));

        jf2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jf2ActionPerformed(evt);
            }
        });
        jf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jf2KeyPressed(evt);
            }
        });
        getContentPane().add(jf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 142, 250, 35));

        jf4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jf4KeyPressed(evt);
            }
        });
        getContentPane().add(jf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 213, 250, 35));

        jf5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jf5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jf5KeyPressed(evt);
            }
        });
        getContentPane().add(jf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 362, 250, 35));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 511, 88, 34));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 591, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 512, 109, 33));

        jc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00AM", "9:30AM", "10:00AM", "2:00PM", "2:30PM", "3:00PM", "5:00PM", "5:30PM", "6:00PM" }));
        getContentPane().add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, -1, 35));

        JComboTheatre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JComboTheatre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboTheatreActionPerformed(evt);
            }
        });
        getContentPane().add(JComboTheatre, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 206, 35));

        jc2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        getContentPane().add(jc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 206, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeimage/background8.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeimage/background8.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 580, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PVR-IMAGE.jpg"))); // NOI18N
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtMovNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtMovNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtMovNameActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jf2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
       
        
        int f1 = jf2.getDocument().getLength();
        int f2 = jf4.getDocument().getLength();
        int f3 = jf5.getDocument().getLength();
       
        if (f1 == 0 || f2 == 0 || f3 == 0 ) {
            JOptionPane.showMessageDialog(this, "Please Enter the Details Properly");

        } 
         else {
            try {
                SQLDao obj = new SQLDao();
                
                
                int n = obj.insertIntoBookingData(jf2.getText(), Long.parseLong(jf4.getText()), movieId , Integer.parseInt(jf5.getText()), jc1.getSelectedItem().toString() ,jc2.getSelectedItem().toString(),theatreIds.get(index) );
                if (n == 0) {
                    
                     JOptionPane.showMessageDialog(this, "Data not Inserted Successfully");
                    
                                        
                } else {
                    
                    JOptionPane.showMessageDialog(this, "Data Inserted Successfully");
                    
                    new payment(n,movieId).setVisible(true);
                    this.dispose();

                   
                }
            } catch (SQLException ex) {
                Logger.getLogger(booking.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        }
        
        
        
        
        
        
        
        
       
       

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jf2.setText(null);
        
        jf5.setText(null);
        jf4.setText(null);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jf2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jf2KeyPressed
          int key = evt.getKeyCode();
        
        if(key >= evt.VK_A && key <= evt.VK_Z  || key == evt.VK_SPACE || key == evt.VK_BACK_SPACE){
            
            jf2.setEditable(true);
            
            
        }else{
            jf2.setEditable(false);
            
            JOptionPane.showMessageDialog(this, " This Field Only Accept Characters ");
    }//GEN-LAST:event_jf2KeyPressed
    } 
    private void jf5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jf5KeyPressed
          int key = evt.getKeyCode();
        
        if(key >= evt.VK_0&& key <= evt.VK_9  || key == evt.VK_SPACE || key == evt.VK_BACK_SPACE){
            
            jf5.setEditable(true);
            
            
        }else{
            jf5.setEditable(false);
            
            JOptionPane.showMessageDialog(this, "  This Field Cannot Accept Characters  " );
    }//GEN-LAST:event_jf5KeyPressed
    }
    private void jf4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jf4KeyPressed
            int key = evt.getKeyCode();
        
        if(key >= evt.VK_0&& key <= evt.VK_9  || key == evt.VK_SPACE || key == evt.VK_BACK_SPACE){
            
            jf4.setEditable(true);
            
            
        }else{
            jf4.setEditable(false);
           
            JOptionPane.showMessageDialog(this, "  This Field Cannot Accept Characters  " );
    }
    }//GEN-LAST:event_jf4KeyPressed

    private void JComboTheatreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboTheatreActionPerformed
        
       index= JComboTheatre.getSelectedIndex();
       System.out.println("Theatre id is "+theatreIds.get(index));
        
        
    }//GEN-LAST:event_JComboTheatreActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboTheatre;
    private javax.swing.JTextField JTxtMovName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JComboBox<String> jc2;
    private javax.swing.JTextField jf2;
    private javax.swing.JTextField jf4;
    private javax.swing.JTextField jf5;
    // End of variables declaration//GEN-END:variables
}
