
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author shreyas
 */
public class movie extends javax.swing.JFrame {

    /**
     * Creates new form movie
     */
    public movie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTxtName = new javax.swing.JTextField();
        JTxtdir = new javax.swing.JTextField();
        JTxtHeroin = new javax.swing.JTextField();
        JTxtRating = new javax.swing.JTextField();
        JtxtDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JTxtHero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTXTLANG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD SHOW");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOVIE NAME                 :  ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DIRECTOR                     :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 244, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ACTORS _HEROINE     :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 250, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   RATING                       :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("   DATE                            :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, 31));

        JTxtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtNameActionPerformed(evt);
            }
        });
        JTxtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxtNameKeyPressed(evt);
            }
        });
        getContentPane().add(JTxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 131, 271, 30));

        JTxtdir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTxtdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtdirActionPerformed(evt);
            }
        });
        JTxtdir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxtdirKeyPressed(evt);
            }
        });
        getContentPane().add(JTxtdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 203, 271, 30));

        JTxtHeroin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTxtHeroin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtHeroinActionPerformed(evt);
            }
        });
        JTxtHeroin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxtHeroinKeyPressed(evt);
            }
        });
        getContentPane().add(JTxtHeroin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 329, 271, 31));

        JTxtRating.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTxtRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtRatingActionPerformed(evt);
            }
        });
        getContentPane().add(JTxtRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 398, 271, 29));

        JtxtDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(JtxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 271, 31));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 611, 90, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("      ADD MOVIES DETAILS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 528, 38));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        JTxtHero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTxtHero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtHeroActionPerformed(evt);
            }
        });
        JTxtHero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxtHeroKeyPressed(evt);
            }
        });
        getContentPane().add(JTxtHero, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 271, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ACTORS _HERO            :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, 31));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" LANGUAGE                    :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, 34));

        JTXTLANG.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTXTLANG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTXTLANGKeyPressed(evt);
            }
        });
        getContentPane().add(JTXTLANG, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 461, 271, 34));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeimage/addmovie.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtdirActionPerformed
          
    }//GEN-LAST:event_JTxtdirActionPerformed

    private void JTxtHeroinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtHeroinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtHeroinActionPerformed

    private void JTxtRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtRatingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new employeeonly().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int f1 = JTxtName.getDocument().getLength();
        int f2 = JTxtdir.getDocument().getLength();
        int f3 = JTxtHero.getDocument().getLength();
        int f4 = JTxtHeroin.getDocument().getLength();
        int f5 = JTxtRating.getDocument().getLength();
        int f6 = JtxtDate.getDocument().getLength();
        int f7 = JTXTLANG.getDocument().getLength();
        if (f1 == 0 || f2 == 0 || f3 == 0 || f4 == 0 || f5 == 0 || f6 == 0 ||f7==0 ) {
            JOptionPane.showMessageDialog(this, "Please Enter the Details Properly");

        } 
         else {
            try {
            SQLDao obj = new SQLDao();
            int n = obj.insertIntoMovieData(JTxtName.getText(), JTxtdir.getText(), JTxtHero.getText(), JTxtHeroin.getText(), Float.parseFloat(JTxtRating.getText()),JTXTLANG.getText(), JtxtDate.getText());

            if (n == 1) {
                JOptionPane.showMessageDialog(this, "Data Inserted Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Data not Inserted Successfully");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(movie.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        }

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTxtHeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtHeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtHeroActionPerformed

    private void JTxtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtNameKeyPressed
        
        int key = evt.getKeyCode();
        
        if(key >= evt.VK_A && key <= evt.VK_Z  || key == evt.VK_SPACE || key == evt.VK_BACK_SPACE){
            
            JTxtName.setEditable(true);
            
            
        }else{
            JTxtName.setEditable(false);
           JOptionPane.showMessageDialog(this, " This Field Only Accept Characters ");
        }
        
        
        
    }//GEN-LAST:event_JTxtNameKeyPressed

    private void JTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtNameActionPerformed

    private void JTxtdirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtdirKeyPressed
          int key = evt.getKeyCode();
        
        if(key >= evt.VK_A && key <= evt.VK_Z  || key == evt.VK_SPACE || key == evt.VK_BACK_SPACE){
            
            JTxtdir.setEditable(true);
            
            
        }else{
            JTxtdir.setEditable(false);
            JOptionPane.showMessageDialog(this, " This Field Only Accept Characters ");
    }//GEN-LAST:event_JTxtdirKeyPressed
    }
    private void JTxtHeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtHeroKeyPressed
          int key = evt.getKeyCode();
        
        if(key >= evt.VK_A && key <= evt.VK_Z  || key == evt.VK_SPACE || key == evt.VK_BACK_SPACE){
            
            JTxtHero.setEditable(true);
            
            
        }else{
            JTxtHero.setEditable(false);
            JOptionPane.showMessageDialog(this, " This Field Only Accept Characters ");
    }//GEN-LAST:event_JTxtHeroKeyPressed
    }
    private void JTxtHeroinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtHeroinKeyPressed
          int key = evt.getKeyCode();
        
        if(key >= evt.VK_A && key <= evt.VK_Z  || key == evt.VK_SPACE || key == evt.VK_BACK_SPACE){
            
            JTxtHeroin.setEditable(true);
            
            
        }else{
            JTxtHeroin.setEditable(false);
            JOptionPane.showMessageDialog(this, " This Field Only Accept Characters ");
    }//GEN-LAST:event_JTxtHeroinKeyPressed
    }
    private void JTXTLANGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTXTLANGKeyPressed
             int key = evt.getKeyCode();
        
        if(key >= evt.VK_A && key <= evt.VK_Z  || key == evt.VK_SPACE || key == evt.VK_BACK_SPACE){
            
            JTxtHero.setEditable(true);
            
            
        }else{
            JTxtHero.setEditable(false);
            JOptionPane.showMessageDialog(this, " This Field Only Accept Characters ");
    } 
    }//GEN-LAST:event_JTXTLANGKeyPressed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTXTLANG;
    private javax.swing.JTextField JTxtHero;
    private javax.swing.JTextField JTxtHeroin;
    private javax.swing.JTextField JTxtName;
    private javax.swing.JTextField JTxtRating;
    private javax.swing.JTextField JTxtdir;
    private javax.swing.JTextField JtxtDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
