
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shreyas
 */
public class show extends javax.swing.JFrame {

    /**
     * Creates new form show
     */
    public show() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jmov_id = new javax.swing.JTextField();
        jtheatrename = new javax.swing.JTextField();
        jmor = new javax.swing.JTextField();
        jnoon = new javax.swing.JTextField();
        jeven = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD SHOW ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                ADD SHOW DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 566, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MOVIE_ ID           :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 123, -1, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("THEATRE_ID        : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 196, -1, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIMINGS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 268, 155, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  MORNING SHOW    :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 329, -1, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("   NOON SHOW          :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("   EVENING SHOW    :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 449, -1, 36));

        jmov_id.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jmov_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmov_idActionPerformed(evt);
            }
        });
        getContentPane().add(jmov_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 195, 226, -1));

        jtheatrename.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtheatrename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtheatrenameActionPerformed(evt);
            }
        });
        getContentPane().add(jtheatrename, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 119, 226, 32));

        jmor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 226, -1));

        jnoon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jnoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnoonActionPerformed(evt);
            }
        });
        getContentPane().add(jnoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 226, -1));

        jeven.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 226, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 529, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 569, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeimage/addtheatre.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmov_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmov_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmov_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int f1 = jmov_id.getDocument().getLength();
        int f2 = jtheatrename.getDocument().getLength();
        int f3 = jmor.getDocument().getLength();
        int f4 = jnoon.getDocument().getLength();
        int f5 = jeven.getDocument().getLength();
       

        if (f1 == 0 || f2 == 0 || f3 == 0 || f4 == 0 || f5 == 0 ) {
            JOptionPane.showMessageDialog(this, "Please Enter the Details Properly");

        } 
         else {
            try {
            SQLDao obj = new SQLDao();
            int n = obj.insertIntoShowData(Integer.parseInt(jmov_id.getText()), Integer.parseInt(jtheatrename.getText()), jmor.getText(), jnoon.getText(), jeven.getText());

            if (n == 1) {
                JOptionPane.showMessageDialog(this, "Data Inserted Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Data not Inserted Successfully");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(movie.class.getName()).log(Level.SEVERE, null, ex);
        }


        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new employeeonly().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtheatrenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtheatrenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtheatrenameActionPerformed

    private void jnoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnoonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnoonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jeven;
    private javax.swing.JTextField jmor;
    private javax.swing.JTextField jmov_id;
    private javax.swing.JTextField jnoon;
    private javax.swing.JTextField jtheatrename;
    // End of variables declaration//GEN-END:variables
}
